In [517]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [518]:
train=pd.read_csv("spaceship-titanic/train.csv")

In [519]:
train.sample()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
2708,2901_01,Earth,False,F/601/P,TRAPPIST-1e,16.0,False,0.0,20.0,0.0,300.0,681.0,Jeanna Vandez,False

In [520]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   str
 1   HomePlanet    8492 non-null   str
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   str
 4   Destination   8511 non-null   str
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   str
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(2), str(5)
memory usage: 891.5+ KB

In [521]:
train.isnull().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [522]:
(train.isnull().sum() / len(train)) * 100

PassengerId     0.000000
HomePlanet      2.312205
CryoSleep       2.496261
Cabin           2.289198
Destination     2.093639
Age             2.059128
VIP             2.335212
RoomService     2.082135
FoodCourt       2.105142
ShoppingMall    2.392730
Spa             2.105142
VRDeck          2.162660
Name            2.300702
Transported     0.000000
dtype: float64

In [523]:
print(train["CryoSleep"].mode())
train["CryoSleep"]=train["CryoSleep"].fillna(False)

0    False
Name: CryoSleep, dtype: object

In [524]:
print(train["HomePlanet"].mode())
train["HomePlanet"]=train["HomePlanet"].fillna("Earth")

0    Earth
Name: HomePlanet, dtype: str

In [525]:
print(train["Cabin"].mode())
train["Cabin"]=train["Cabin"].fillna("G/734/S")

0    G/734/S
Name: Cabin, dtype: str

In [526]:
print(train["Destination"].mode())
train["Destination"]=train["Destination"].fillna("TRAPPIST-1e")

0    TRAPPIST-1e
Name: Destination, dtype: str

In [527]:
print(train["VIP"].mode())
train["VIP"]=train["VIP"].fillna(False)

0    False
Name: VIP, dtype: object

In [528]:
# Numerical columns
# filled every null value of num or numerical columns at once 
# the fillna will find the mean of every train num columns 
num_cols = ['Age', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']
train[num_cols] = train[num_cols].fillna(train[num_cols].mean())

In [529]:
train=train.drop(columns=["Name"])

In [530]:
test=pd.read_csv("spaceship-titanic/test.csv")

In [531]:
test.sample()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
1300,2794_02,Mars,False,F/579/P,TRAPPIST-1e,22.0,False,842.0,NaN,431.0,52.0,0.0,Pefox Apie

In [532]:
test.info()

<class 'pandas.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   4277 non-null   str
 1   HomePlanet    4190 non-null   str
 2   CryoSleep     4184 non-null   object
 3   Cabin         4177 non-null   str
 4   Destination   4185 non-null   str
 5   Age           4186 non-null   float64
 6   VIP           4184 non-null   object
 7   RoomService   4195 non-null   float64
 8   FoodCourt     4171 non-null   float64
 9   ShoppingMall  4179 non-null   float64
 10  Spa           4176 non-null   float64
 11  VRDeck        4197 non-null   float64
 12  Name          4183 non-null   str
dtypes: float64(6), object(2), str(5)
memory usage: 434.5+ KB

In [533]:
test.isnull().sum()

PassengerId       0
HomePlanet       87
CryoSleep        93
Cabin           100
Destination      92
Age              91
VIP              93
RoomService      82
FoodCourt       106
ShoppingMall     98
Spa             101
VRDeck           80
Name             94
dtype: int64

In [534]:
(test.isnull().sum() / len(test)) * 100

PassengerId     0.000000
HomePlanet      2.034136
CryoSleep       2.174421
Cabin           2.338087
Destination     2.151040
Age             2.127660
VIP             2.174421
RoomService     1.917232
FoodCourt       2.478373
ShoppingMall    2.291326
Spa             2.361468
VRDeck          1.870470
Name            2.197802
dtype: float64

In [535]:
print(test["HomePlanet"].mode())
test["HomePlanet"]=test["HomePlanet"].fillna("Earth")

0    Earth
Name: HomePlanet, dtype: str

In [536]:
print(test["CryoSleep"].mode())
test["CryoSleep"]=test["CryoSleep"].fillna(False)

0    False
Name: CryoSleep, dtype: object

In [537]:
print(test["Cabin"].mode())
test["Cabin"]=test["Cabin"].fillna("G/160/P")

0    G/160/P
Name: Cabin, dtype: str

In [538]:
print(test["Destination"].mode())
test["Destination"]=test["Destination"].fillna("TRAPPIST-1e")

0    TRAPPIST-1e
Name: Destination, dtype: str

In [539]:
print(test["VIP"].mode())
test["VIP"]=test["VIP"].fillna(False)

0    False
Name: VIP, dtype: object

In [540]:
number_cols = ['Age', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']
test[number_cols] = test[number_cols].fillna(test[number_cols].mean())

In [541]:
test=test.drop(columns=["Name"])

In [542]:
test.duplicated().sum()

np.int64(0)

In [543]:
from sklearn.model_selection import train_test_split
rd=train_test_split

In [552]:
X_train, X_test, y_train, y_test=rd(X,y,test_size=0.2,random_state=42)

NameError: name 'X' is not defined

In [ ]:
# ENCORDING converying cat to num 
# We encode categorical text data into numbers because most machine learning algorithms can only work with numbers, not text.
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()

In [ ]:
train.columns

Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
       'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck',
       'Transported'],
      dtype='str')

In [ ]:
train["Destination"]=LE.fit_transform(train["Destination"])
print(train["Destination"])

0       2
1       2
2       2
3       2
4       2
       ..
8688    0
8689    1
8690    2
8691    0
8692    2
Name: Destination, Length: 8693, dtype: int64

In [ ]:
train["Cabin"]=LE.fit_transform(train["Cabin"])
print(train["Cabin"])

0        149
1       2184
2          1
3          1
4       2186
        ...
8688     146
8689    5280
8690    5285
8691    2131
8692    2131
Name: Cabin, Length: 8693, dtype: int64

In [ ]:
train["PassengerId"]=LE.fit_transform(train["PassengerId"])
print(train["PassengerId"])

0          0
1          1
2          2
3          3
4          4
        ...
8688    8688
8689    8689
8690    8690
8691    8691
8692    8692
Name: PassengerId, Length: 8693, dtype: int64

In [ ]:
train["VIP"]=LE.fit_transform(train["VIP"])
print(train["VIP"])

0       0
1       0
2       1
3       0
4       0
       ..
8688    1
8689    0
8690    0
8691    0
8692    0
Name: VIP, Length: 8693, dtype: int64

In [ ]:
train["CryoSleep"]=LE.fit_transform(train["CryoSleep"])
print(train["CryoSleep"])

0       0
1       0
2       0
3       0
4       0
       ..
8688    0
8689    1
8690    0
8691    0
8692    0
Name: CryoSleep, Length: 8693, dtype: int64

In [ ]:
train["HomePlanet"]=LE.fit_transform(train["HomePlanet"])
print(train["HomePlanet"])

0       1
1       0
2       1
3       1
4       0
       ..
8688    1
8689    0
8690    0
8691    1
8692    1
Name: HomePlanet, Length: 8693, dtype: int64

In [ ]:
train["Transported"]=LE.fit_transform(train["Transported"])
print(train["Transported"])

0       0
1       1
2       0
3       0
4       1
       ..
8688    0
8689    0
8690    1
8691    0
8692    1
Name: Transported, Length: 8693, dtype: int64

In [ ]:
train.sample()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
785,785,0,0,6156,0,42.0,0,0.0,0.0,739.0,0.0,0.0,1

In [ ]:
print(train[["VIP","CryoSleep"]].dtypes)

VIP          int64
CryoSleep    int64
dtype: object

In [ ]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   int64
 1   HomePlanet    8693 non-null   int64
 2   CryoSleep     8693 non-null   int64
 3   Cabin         8693 non-null   int64
 4   Destination   8693 non-null   int64
 5   Age           8693 non-null   float64
 6   VIP           8693 non-null   int64
 7   RoomService   8693 non-null   float64
 8   FoodCourt     8693 non-null   float64
 9   ShoppingMall  8693 non-null   float64
 10  Spa           8693 non-null   float64
 11  VRDeck        8693 non-null   float64
 12  Transported   8693 non-null   int64
dtypes: float64(6), int64(7)
memory usage: 883.0 KB

In [ ]:
train.tail()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported
8688,8688,1,0,146,0,41.0,1,0.0,6819.0,0.0,1643.0,74.0,0
8689,8689,0,1,5280,1,18.0,0,0.0,0.0,0.0,0.0,0.0,0
8690,8690,0,0,5285,2,26.0,0,0.0,0.0,1872.0,1.0,0.0,1
8691,8691,1,0,2131,0,32.0,0,0.0,1049.0,0.0,353.0,3235.0,0
8692,8692,1,0,2131,2,44.0,0,126.0,4688.0,0.0,0.0,12.0,1

In [545]:
X_train=train.iloc[:,:-1]

In [ ]:
y_train=train["Transported"]

In [ ]:
from sklearn.linear_model import LogisticRegression
LOGR=LogisticRegression()

In [ ]:
LOGR.fit(X_train,y_train)

/usr/local/python/3.12.1/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
LOGR.predict(X_train)

array([1, 0, 0, ..., 1, 0, 1], shape=(8693,))

In [ ]:
LOGR.score(X_train,y_train)

0.7825836880248476

In [ ]:
test.columns

Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
       'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck'],
      dtype='str')

In [ ]:
test.sample()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
788,788,0,0,1793,2,28.658146,0,0.0,0.0,406.0,298.0,12.0

In [ ]:
test["Destination"]=LE.fit_transform(test["Destination"])
print(test["Destination"])

0       2
1       2
2       0
3       2
4       2
       ..
4272    2
4273    2
4274    0
4275    2
4276    1
Name: Destination, Length: 4277, dtype: int64

In [ ]:
test["Cabin"]=LE.fit_transform(test["Cabin"])
print(test["Cabin"])

0       2784
1       1867
2        257
3        259
4       1940
        ...
4272    2679
4273    2691
4274     602
4275     603
4276    2680
Name: Cabin, Length: 4277, dtype: int64

In [ ]:
test["HomePlanet"]=LE.fit_transform(test["HomePlanet"])
print(test["HomePlanet"])

0       0
1       0
2       1
3       1
4       0
       ..
4272    0
4273    0
4274    2
4275    1
4276    0
Name: HomePlanet, Length: 4277, dtype: int64

In [ ]:
test["PassengerId"]=LE.fit_transform(test["PassengerId"])
print(test["PassengerId"])

0          0
1          1
2          2
3          3
4          4
        ...
4272    4272
4273    4273
4274    4274
4275    4275
4276    4276
Name: PassengerId, Length: 4277, dtype: int64

In [ ]:
test["CryoSleep"]=LE.fit_transform(test["CryoSleep"])
print(test["CryoSleep"])

0       1
1       0
2       1
3       0
4       0
       ..
4272    1
4273    0
4274    1
4275    0
4276    1
Name: CryoSleep, Length: 4277, dtype: int64

In [ ]:
test["VIP"]=LE.fit_transform(test["VIP"])
print(test["VIP"])

0       0
1       0
2       0
3       0
4       0
       ..
4272    0
4273    0
4274    0
4275    0
4276    0
Name: VIP, Length: 4277, dtype: int64

In [547]:
X_test=test.iloc[:,1:]